In [1]:
# 1-D array used as vector
# 2-D array used as matrix
#X=[3,5]--> 3 is projection of vector X in x axis and 5 is projection of vectory X in y axis

In [3]:
import numpy as np
from scipy import linalg

In [3]:
mat1=np.array([[1,2,4],[4,5,6]]) # 2D array or matrix 2x3
mat2=np.array([[0.5],[1]])#2X1 matrix


In [4]:
mat1

array([[1, 2, 4],
       [4, 5, 6]])

In [5]:
mat2

array([[0.5],
       [1. ]])

###### Matrix Operations

In [6]:
# scales all element of matrix by 2 times
mat3=2*mat1
mat3

array([[ 2,  4,  8],
       [ 8, 10, 12]])

In [7]:
# Same as mat 3
mat4=mat1+mat1
mat4

array([[ 2,  4,  8],
       [ 8, 10, 12]])

In [8]:
#mat1& mat2 are matrix are not of similar direction- linear algebra operation on addition and subtraction is invalid
# but numpy handles it gracfully
mat5=mat1+mat2
mat5

array([[1.5, 2.5, 4.5],
       [5. , 6. , 7. ]])

In [9]:
# this is general operation - not a valid matrix opertaion
mat6=mat1*mat2
mat6

array([[0.5, 1. , 2. ],
       [4. , 5. , 6. ]])

In [10]:
# In order to multiply to matrices no. of columns in the first matrix should be equal to the no. of rows in the 2nd matrix

In [11]:
mat1.shape

(2, 3)

In [12]:
mat2.shape

(2, 1)

In [13]:
# Gives Error
mat7=mat1.dot(mat2)

ValueError: shapes (2,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)

In [14]:
# same with mat1 dot mat1
mat8=mat1.dot(mat1)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [15]:
mat1.T.shape

(3, 2)

In [16]:
# dot product of 3x2 matrix with 2x3 matrix ( 2/2 cancels out -> returns 3X3 matrix)
mat9=mat1.T.dot(mat1)
mat9


array([[17, 22, 28],
       [22, 29, 38],
       [28, 38, 52]])

In [17]:
# dot product of 2x3 matrix with 3X2 matrix ( 3/3 cancels out -> returns 2X2 matrix)
mat10=mat1.dot(mat1.T)
mat10

array([[21, 38],
       [38, 77]])

In [18]:
# Both above are symetrical matrix( when you get dor product of a matrix with its transpose - you get symmetrical matrix)

In [19]:
#DOT product of vector

In [20]:
mat2.shape,mat2.T.shape

((2, 1), (1, 2))

In [21]:


# dot product of mat2 with itself will show error
mat11=mat2.dot(mat2)

ValueError: shapes (2,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)

In [22]:
# way is to transpose and then multipluy x.y =x.T.dot(y), id x=[x1,x2] then x.T.dot(x)=x1*x1+x2*x2

In [23]:
mat12=mat2.T.dot(mat2)
mat12

array([[1.25]])

In [24]:
# Consine is measure of angles between the vectors or sinilarity in direction of vectors. When angle 90 degree i.e vector is orthogonal, cosine is 0
#i.e dot product is 0, In case cosine is 1, it means vectors point in same direction.
# for same vectors cosine is 1

In [25]:
# Cosine angle b/w x and y is x.dot(y)/(norm(x)* norm(y))

###### Special matrix

In [26]:
# Deteminant of a matrix- possible for square matrix only

In [27]:
A=np.array([[2,3,4],[1,5,3],[2,8,3]])
A

array([[2, 3, 4],
       [1, 5, 3],
       [2, 8, 3]])

In [28]:
# Deteminant=2*(5*3-8*3)-3(1*3-2*3)+4(1*8-5*2)=-17

In [29]:
np.linalg.det(A)

-16.999999999999993

In [30]:
# Minor of 1 

In [31]:
A_minor_1=np.array([[3,4],[8,3]])
A_minor_1

array([[3, 4],
       [8, 3]])

In [32]:
# this is 9-32=-23

In [33]:
# Cofactor will be ( erevrse sign of reverse diagonal elements)
A_cofactor_1=np.array([[3,-4],[-8,3]])
A_cofactor_1

array([[ 3, -4],
       [-8,  3]])

In [34]:
#for 3 X3--> change sign  of elements apart from principla diagonal elemet and reverse diagonal element

In [35]:
# Adjoint of matrix A is  transpose of cofactor of A

In [36]:
# Inverse of a matrix can be found only if matrix is linearly independent det(A) should be 0 in case of linear independence
# rank should be full

In [37]:
# matrix dot product with its inverse is identity matrix

In [38]:

mat13=np.array([[14,32],[32,77]])
mat13

array([[14, 32],
       [32, 77]])

In [39]:
mat14=linalg.inv(mat13)
mat14

array([[ 1.42592593, -0.59259259],
       [-0.59259259,  0.25925926]])

In [40]:
mat13.dot(mat14) # identity matric. Dot product of matrix with its dot product is identity matrix

array([[1., 0.],
       [0., 1.]])

In [41]:
mat15=np.array([[17,22,27],[22,29,36],[27,36,45]])
mat15

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [42]:
2*mat15[1,:]-mat15[0,:]

array([27, 36, 45])

In [43]:
mat15[2,:]

array([27, 36, 45])

In [44]:
# 3rd row is linear combination of 1st and 2nd row- which means matrix is not of full rank (3)
# Inverse cant be taken

In [45]:
linalg.inv(mat15)

LinAlgError: singular matrix

In [46]:
np.linalg.matrix_rank(mat15) # rank of matrix

2

In [47]:
mat16=np.array([[17,22,27],[22,29,36],[1,13,17]])
mat16

array([[17, 22, 27],
       [22, 29, 36],
       [ 1, 13, 17]])

In [48]:
np.linalg.matrix_rank(mat16) # rank of matrix

3

In [49]:
mat17=linalg.inv(mat16)
mat17

array([[-0.34722222,  0.31944444, -0.125     ],
       [ 4.69444444, -3.63888889,  0.25      ],
       [-3.56944444,  2.76388889, -0.125     ]])

In [50]:
mat16.dot(mat17)

array([[ 1.00000000e+00, -1.33226763e-15, -1.38777878e-17],
       [-1.95399252e-14,  1.00000000e+00, -6.10622664e-16],
       [-1.33226763e-15,  3.10862447e-15,  1.00000000e+00]])

In [51]:
 #norm gives maginitude of a vector for matrices it is sum of square of each element and then sq root
linalg.norm(mat2)

1.118033988749895

In [52]:
linalg.norm(mat2,'fro') # frobenius

1.118033988749895

In [53]:
linalg.norm(mat2,2) # l2 norm

1.118033988749895

In [54]:
linalg.norm(mat2,1)# manhatten distance-L1 norm sum of absolute value

1.5

In [55]:
linalg.norm(mat2,np.inf) # L infinite norm will be larget element

1.0

In [56]:
linalg.norm(mat17)

7.481690614055385

In [57]:
a=np.array([3,4]) # vector a
b=np.array([30,40])# vector b

In [58]:
#magnitude of vector a
linalg.norm(a)

5.0

In [59]:
#magnitude of vector b
linalg.norm(b)

50.0

In [60]:
#direction of vector a
u=a/linalg.norm(a)
u

array([0.6, 0.8])

In [61]:
#direction of vector b
v=b/linalg.norm(b)
v

array([0.6, 0.8])

In [62]:
#u, v both are unit vectors
linalg.norm(u), linalg.norm(v)

(1.0, 1.0)

In [63]:
# Consine is measure of angles between the vectors or sinilarity in direction of vectors. When angle 90 degree i.e vector is orthogonal, cosine is 0
#i.e dot product is 0, In case cosine is 1, it means vectors point in same direction.
# for same vectors cosine is 1

In [64]:
import scipy
from scipy import spatial
scipy.spatial.distance.cosine(mat2,mat2) # same vector hence 0

0.0

In [65]:
scipy.spatial.distance.cosine(mat2,2*mat2) # same direction hence 0

0.0

In [66]:
scipy.spatial.distance.cosine(mat2,-mat2) # Opposite direction

2.0

In [67]:
scipy.spatial.distance.cosine(mat2,mat2+5)

0.03847605235917684

In [68]:
scipy.spatial.distance.cosine(mat2,mat2.T)

0.0

In [69]:
# Eigen value decomposition
# mat15 is of rank 2 hence we expect 2 eigen vecor 3rd will be 0
# Eigen Vectors are such vectors which when multiplied by a vector stretched the vector by lambda constant
#AX=lambda.X, X is eigen vector, Lambda is eigen value--> only scaling no rotation
eigVals,eigVecs=linalg.eig(mat15)

In [70]:
eigVals # 3rd one is very small almost 0

array([ 9.04026725e+01+0.j,  5.97327474e-01+0.j, -4.34052215e-15+0.j])

In [71]:
# matrix B
B=np.array([[1,2],[2,4]])
B

array([[1, 2],
       [2, 4]])

In [72]:
# vector V
v=np.array([1,1])

In [73]:
v1=B.dot(v)
v1

array([3, 6])

In [74]:
#this is same as
v1/3

array([1., 2.])

In [75]:
# lets see another vector v2
v2=np.array([1,2])
v2

array([1, 2])

In [76]:
v3=B.dot(v2)
v3

array([ 5, 10])

In [77]:
v3/5

array([1., 2.])

In [78]:
# this is same as v2, which means v2 when multiplied by Matrix B returns the same vector v2 scaled .
#indicating that v2 is a eigen vector and 5 is eigen value

In [142]:
a=np.array([0.5,0.5])

In [143]:
b=np.array([0.1,0.1])

In [144]:
a.dot(b)

0.1

In [147]:
a.dot(b)/(linalg.norm(a)*linalg.norm(b))

1.0

In [79]:
a1=np.array([5,4])
b1=np.array([4,5])

In [80]:
a1.dot(b1)/(linalg.norm(a1)*linalg.norm(b1))

0.975609756097561

In [81]:
c1=np.array([4,4])

In [82]:
c1.dot(b1)/(linalg.norm(c1)*linalg.norm(b1))

0.9938837346736188

In [3]:
x=np.array([1,-1,0])
y=np.array([-2,1,1])

In [4]:
x.dot(y)/(linalg.norm(x)*linalg.norm(y))

-0.8660254037844387

In [5]:
np.sqrt(12)

3.4641016151377544

In [7]:
np.sqrt(2)*np.sqrt(6)

3.4641016151377544

In [10]:
linalg.norm(x)*linalg.norm(y)

3.4641016151377544

In [11]:
x.dot(y)

-3

In [25]:
a1=np.array([5,4])
b1=np.array([4,5])

In [26]:
a1.dot(b1)/(linalg.norm(a1)*linalg.norm(b1))

0.975609756097561

In [27]:
a1=np.array([4,4])
b1=np.array([5,5])

In [28]:
a1.dot(b1)/(linalg.norm(a1)*linalg.norm(b1))

0.9999999999999998

In [31]:
a1=np.array([1,1])
b1=np.array([5,5])

In [32]:
a1.dot(b1)/(linalg.norm(a1)*linalg.norm(b1))

0.9999999999999998

In [10]:
a1=np.array([[1,3,0],[2,10,2],[4,1,1]])
b1=np.array([[1,0,-1],[1,0.1,-1],[1,0,-1]])
b1.T

array([[ 1. ,  1. ,  1. ],
       [ 0. ,  0.1,  0. ],
       [-1. , -1. , -1. ]])

In [13]:
b1.T.dot(a1)

array([[  7. ,  14. ,   3. ],
       [  0.2,   1. ,   0.2],
       [ -7. , -14. ,  -3. ]])

In [18]:
a1=np.array([1,1])
b1=np.array([5,5])

In [15]:
a1.dot(b1)

10

In [35]:
a1=np.array([[3,0,1],[2,6,2],[2,4,1]])
b1=np.array([[-1,0,1],[-2,0,2],[-1,0,1]])

In [36]:
a1

array([[3, 0, 1],
       [2, 6, 2],
       [2, 4, 1]])

In [37]:
b1

array([[-1,  0,  1],
       [-2,  0,  2],
       [-1,  0,  1]])

In [38]:
np.dot(a1,b1)

array([[ -4,   0,   4],
       [-16,   0,  16],
       [-11,   0,  11]])

In [39]:
a1*b1

array([[-3,  0,  1],
       [-4,  0,  4],
       [-2,  0,  1]])

In [21]:
np.dot(a1,b1)

array([[  4. ,   0.3,  -4. ],
       [ 14. ,   1. , -14. ],
       [  6. ,   0.1,  -6. ]])

In [22]:
np.dot()


array([[ 1.,  0., -0.],
       [ 2.,  1., -2.],
       [ 4.,  0., -1.]])